# Generated by Django 5.0.6 on 2024-06-10 17:23

import django.db.models.deletion
import drawing.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudiogramCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FilePathField(path=drawing.models.basepath)),
                ('scaling', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AudiogramPollSubmission',
            fields=[
                ('submit_ID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(max_length=75)),
                ('position', models.CharField(choices=[('ENTPS', 'ENT physician'), ('ENTSG', 'ENT surgeon'), ('SPTP', 'speech therapist'), ('AUD', 'audiologist'), ('HATC', 'hearing aid technician'), ('OTHER', 'other')], max_length=10, verbose_name='user_position')),
                ('submit_timestamp', models.DateTimeField()),
                ('points', models.JSONField(verbose_name='user_set_raw_points')),
                ('audiogram_canvas', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='drawing.audiogramcanvas')),
            ],
        ),
    ]
