# Generated by Django 5.0.6 on 2024-06-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0002_alter_audiogrampollsubmission_submit_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiogrampollsubmission',
            name='audiogram_canvas',
        ),
    ]
